services:
  mysql: 
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - dbfile:/var/lib/mysql
    networks:
      - app
  
  wp:
    image: wordpress
    container_name: wp
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - www-html:/var/www/html
    networks:
      - app
  
  nginx:
    image: nginx
    depends_on:
      - wp
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - www-html:/var/www/html
      - ./nginx-conf.d:/etc/nginx/conf.d
    networks:
      - app
    
volumes:
  www-html:
  dbfile:

networks:
  app:
    driver: bridge
